Welcome to your first Python Assignment! In this lab we will get our hands dirty with Python and the NumPy library. We will also work with loops and indexing. You will need a Google Account to save your assignments.


Please make a copy of this file to save your progress. Try pressing CTRL (or CMD) + S and it should ask you to save this file in Google Drive. The files will be autmatically saved under Colab Notebooks folder in your Google Drive.

**Instructions:**
*   You only need to write code between the **### START CODE HERE ###** and **### END CODE HERE ###** comments. After writing your code, you can run the cell by either pressing "SHIFT"+"ENTER" or by clicking on "Run Cell" (denoted by a play symbol) in the left side of the notebook. 

**Learning Objectives**
* Use GoogleColab notebook for future assignments
*Use NumPy functions and its matrix/vector operations`





## About GoogleColab ##

GoogleColab is an interactive coding environment embedded in a webpage and will use it for future Machine Learning Projects.

**Exercise**: Set test to `"Hello World"` in the cell below to print "Hello World" and run the two cells below.

In [1]:
### START CODE HERE ###
test = ""
### END CODE HERE ###

In [2]:
print ("test: " + test)

test: 


**Expected output**:
test: Hello World

**What you need to remember**:
* Run your cells using SHIFT+ENTER (or "Run the focused cell")
* Write code in the designated areas
* Do not modify the code outside of the designated areas

#PART 1: Working with Numpy

The syntax for all operations can be found on [NumPy.org](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html), or a google search.

In [3]:
#Import NumPy library
import numpy

#It could also be imported as import numpy as np for convenience

In [4]:
#Define an row-vector/array
arr1 = numpy.array([1, 2, 3])
arr2 = numpy.array([3, 1, 2])

#Define a matrix
mat1 = numpy.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat2 = numpy.matrix([[5, 7, 6], [3, 1, 2], [4, 8, 9]])

In [5]:
print('Vectors = ')
print(arr1)
print(arr2)

print('matrix 1 = ')
print(mat1)

print('matrix = ')
print(mat2)

Vectors = 
[1 2 3]
[3 1 2]
matrix 1 = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix = 
[[5 7 6]
 [3 1 2]
 [4 8 9]]


Let's now perform some matrix operations.

In [6]:
#Matrix addition
mat_add = mat1 + mat2

print('Addition: ')
print(mat_add)

Addition: 
[[ 6  9  9]
 [ 7  6  8]
 [11 16 18]]


In [7]:
#Matrix Subtraction
mat_sub = mat1 - mat2

print('Subtraction: ')
print(mat_sub)

Subtraction: 
[[-4 -5 -3]
 [ 1  4  4]
 [ 3  0  0]]


In [8]:
#Matrix multiplication
mat_mul_1 = numpy.matmul(mat1, mat2) #or mat1*mat2
mat_mul_2 = numpy.multiply(mat1, mat2)

print("")

print('Matrix multiplication: ')
print('Method 1: ')
print(mat_mul_1)

print('Method 2: ')
print(mat_mul_2)


Matrix multiplication: 
Method 1: 
[[ 23  33  37]
 [ 59  81  88]
 [ 95 129 139]]
Method 2: 
[[ 5 14 18]
 [12  5 12]
 [28 64 81]]


####QUESTION####
**Why did we get different matrix multiplication values? Are the two functions different? Double click this tab to write the answer.**

Your answer:


Try solving the next bit of code using the above as reference. Define one array and two matrices.

In [9]:
### START CODE HERE ###
arr1 = 

mat1 = 
mat2 = 
### END CODE HERE ###

SyntaxError: ignored

In [ ]:
print('Array = ')
print(arr1)

print('matrix 1 = ')
print(mat1)

print('matrix = ')
print(mat2)

Try the next bit on your own to work with NumPy matrix functions.

In [ ]:
#Matrix addition

### START CODE HERE ###
mat_add = 
### END CODE HERE ###

print('Addition: ')
print(mat_add)

In [ ]:
#Matrix Subtraction

### START CODE HERE ###
mat_sub = 
### END CODE HERE ###

print('Subtraction: ')
print(mat_sub)

In [ ]:
#Matrix multiplication

### START CODE HERE ###
mat_mul_1 = numpy.
### END CODE HERE ###

print('Matrix multiplication: ')
print(mat_mul_1)

#Matrix Elementwise Multiplication

### START CODE HERE ###
mat_mul_2 = numpy.
### END CODE HERE ###

print('Element wise multiplication: ')
print(mat_mul_2)

General matrix operations such as finding the determinant, inverse, transpose, and reshaping the matrix shape.

Let's redefine a non-square matrix.

In [ ]:
mat_notsquare = numpy.matrix([[1, 2, 3], [4, 5, 6]])

In [ ]:
#Print the shape of 'mat_notsquare'
print(mat_notsquare)
print(numpy.shape(mat_notsquare))

In [ ]:
#Let's reshape the matrix
#Reshaping it to 1x6 vector
mat_reshaped = numpy.reshape(mat_notsquare, (1, 6))
print(mat_reshaped)
print(numpy.shape(mat_reshaped))

print("")

#Reshaping it to 3x2 matrix
mat_reshaped = numpy.reshape(mat_notsquare, (3, 2))
print(mat_reshaped)
print(numpy.shape(mat_reshaped))

In [ ]:
#Finding the transpose of a matrix
transpose_mat = numpy.transpose(mat_notsquare)
print(transpose_mat)

#Transpose it again
print("Second time transposition gives us the original matrix")
transpose_mat = numpy.transpose(transpose_mat)
print(transpose_mat)

In [ ]:
#Now, let's find the determinant of a matrix
#Define a square matrix
mat_square = numpy.matrix([[1, 2, 3], [6, 5, 10], [7, 8, 9]])
determinant = numpy.linalg.det(mat_square)

print(determinant)

####Question####
**Try to find the inverse of the matrix of the matrix by referring to this documentation: [NumPy matrix inverse](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html).**

Hint: replace 'det' by 'inv'. But, do check the documentation listed here.

In [ ]:
mat_inv = numpy.
print(mat_inv)

**Concept of NumPy Broadcasting**

A very important concept to understand in numpy is "broadcasting". It is very useful for performing mathematical operations between arrays of different shapes.

In [ ]:
arr = numpy.array([1, 2, 3])
mat = numpy.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
print("Shape of arr:")
print(numpy.shape(arr))

print("Array: ")
print(arr)

In [ ]:
print("Shape of mat:")
print(numpy.shape(mat))

print("Matrix: ")
print(mat)

Try running the next code and see what happens.

In [ ]:
subtraction = mat - arr

print(subtraction)

####QUESTION####

**Unusual? A 3x1 vector subtracted from 3x3 matrix? How did the function work to return a value even when we are subtracting a (3, 1) array from (3, 3) matrix? Think about it and answer the question.**


Hint:
Refer to this [broadcasting documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

Also, this 3 minute video is great to learn about this.
https://www.youtube.com/watch?v=J-SjUu890hw

YOUR ANSWER:


#PART 2: Loops

Great job, completing the first half! Now, we will move onto defining for-loop and while-loop.

**While Loop**

Let's print out 10 numbers from 1 to 10.

In [ ]:
#Basic structure of while loop
num = 1
while num <= 10:
  print(num)
  num = num + 1

print('!!!Notice the indentation after the first loop statement in the code.\nPython thinks the commands are inside the loop until the indentation ends.')
print("No need for 'end' statement")

**For Loop**

Let's try doing the same but with a for-loop. The range() function will come in handy while we do this. Run the next cell.

In [ ]:
#range(n) generates an array of range 0->(n-1). We will store this value in the variable range_num.
range_num = range(10)

#To access this value we will use a for-loop
for num in range_num:
  print(num)

print("This printed off 0-9 because it generates integers from 0-9.")

**Important Note**
The array indexing in Python starts out at 0. Demonstration below.


In [ ]:
arr = numpy.random.rand(3)
print('The array is:', arr)

print('First element of arr is arr[0]:', arr[0])
print('Second element of arr is arr[1:]', arr[1])
print('And so on...')

Try implementing your own while and for-loop to print even numbers from 0-20.

While loop

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

For-loop

Hint: You will have to use 'if' command to see if the number is divisible by 2 or not. Use the '%' command to find the remainder. If remainder is 0, then even.

Structure:

for num in range(your_num):
    if num % 2 == 0
        print(num)


In [ ]:
### START CODE HERE ###

### END CODE HERE ###

**Expected output for both cells:**
0
2
4
6
8
10
12
14
16
18
20

